#version: '3'

services:
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"   # Web UI
      - "1025:1025"   # SMTP port

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app:/app

  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./app:/app

  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'secret123'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'secret123'
      MYSQL_DATABASE: 'haarlem_festival_v3'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql

volumes:
  mysqldata: {}
